### ISSUE TITLE
启动后登陆后台提示 Unauthorized request: no authentication given

### ISSUE THREAD

**Issue by bruce48x** [fomenyesu/egg-restapi-module-tool#23]
刚接触 egg 和 react，
用这个项目学习，
点击登录（账号密码默认的 admin 和 123 ）提示 `Unauthorized request: no authentication given` 这个错误，
能帮我解答是哪里不对吗
详细的日志：
```
2018-09-26 17:06:40,958 WARN 42221 [-/127.0.0.1/-/18ms POST /user/authorize?t=1537952800909] nodejs.unauthorized_request: Unauthorized request: no authentication given
    at new UnauthorizedRequestError (/Users/wangql/src/egg-restapi-module-tool/node_modules/oauth2-server/lib/errors/unauthorized-request-error.js:28:14)
    at AuthenticateHandler.getTokenFromRequest (/Users/wangql/src/egg-restapi-module-tool/node_modules/oauth2-server/lib/handlers/authenticate-handler.js:132:9)
    at AuthenticateHandler.<anonymous> (/Users/wangql/src/egg-restapi-module-tool/node_modules/oauth2-server/lib/handlers/authenticate-handler.js:68:19)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at AuthenticateHandler.handle (/Users/wangql/src/egg-restapi-module-tool/node_modules/oauth2-server/lib/handlers/authenticate-handler.js:67:6)
    at OAuth2Server.authenticate (/Users/wangql/src/egg-restapi-module-tool/node_modules/oauth2-server/lib/server.js:43:6)
    at OAuth2.execute (/Users/wangql/src/egg-restapi-module-tool/node_modules/egg-oauth2-server/lib/server.js:86:41)
    at /Users/wangql/src/egg-restapi-module-tool/node_modules/egg-oauth2-server/lib/server.js:108:32
    at dispatch (/Users/wangql/src/egg-restapi-module-tool/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wangql/src/egg-restapi-module-tool/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/wangql/src/egg-restapi-module-tool/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/wangql/src/egg-restapi-module-tool/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/wangql/src/egg-restapi-module-tool/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/wangql/src/egg-restapi-module-tool/node_modules/koa-router/lib/router.js:351:31)
    at dispatch (/Users/wangql/src/egg-restapi-module-tool/node_modules/koa-compose/index.js:42:32)
    at createGenerator (/Users/wangql/src/egg-restapi-module-tool/node_modules/koa-convert/index.js:24:16)
    at createGenerator.next (<anonymous>)
    at onFulfilled (/Users/wangql/src/egg-restapi-module-tool/node_modules/co/index.js:65:19)
    at /Users/wangql/src/egg-restapi-module-tool/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (/Users/wangql/src/egg-restapi-module-tool/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/wangql/src/egg-restapi-module-tool/node_modules/co/index.js:118:63)
    at next (/Users/wangql/src/egg-restapi-module-tool/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/wangql/src/egg-restapi-module-tool/node_modules/co/index.js:69:7)
    at /Users/wangql/src/egg-restapi-module-tool/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (/Users/wangql/src/egg-restapi-module-tool/node_modules/co/index.js:50:10)
    at converted (/Users/wangql/src/egg-restapi-module-tool/node_modules/koa-convert/index.js:17:15)
    at dispatch (/Users/wangql/src/egg-restapi-module-tool/node_modules/koa-compose/index.js:42:32)
    at fn (/Users/wangql/src/egg-restapi-module-tool/node_modules/egg-core/lib/loader/mixin/middleware.js:107:29)
    at dispatch (/Users/wangql/src/egg-restapi-module-tool/node_modules/koa-compose/index.js:42:32)
    at createGenerator (/Users/wangql/src/egg-restapi-module-tool/node_modules/koa-convert/index.js:24:16)
    at createGenerator.next (<anonymous>)
    at onFulfilled (/Users/wangql/src/egg-restapi-module-tool/node_modules/co/index.js:65:19)
    at /Users/wangql/src/egg-restapi-module-tool/node_modules/co/index.js:54:5
statusCode: 401
status: 401
code: 401
message: "Unauthorized request: no authentication given"
name: "unauthorized_request"
pid: 42221
hostname: blessdeiMac.local
```

**Comment by fomenyesu** [comment]
如果用cnpm install 安装的话，需要改用 npm install  。 oauth组件cnpm的版本有问题。

**Comment by fomenyesu** [comment]
close without further question.
